### PR TITLE
Remove EVENT_TIME_CHANGED const

### LINKED ISSUE #45: HA Strava fails to startup with HA 2022.5
HA Strava was all working fine on 2022.4.7....testing on 2022.5 and getting the following error on start

Setup failed for custom integration ha_strava: Unable to import component: cannot import name 'EVENT_TIME_CHANGED' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

Any idea what might be causing the issue...have had a look about and cant see anyone else reporting

### PR DESCRIPTION
**Pull request by youdroid**
Hi,

With HA 2022.5.X, the EVENT_TIME_CHANGED constant was removed, see https://developers.home-assistant.io/blog/2022/04/20/saying-goodbye-to-event_time_changed.

This PR removes this event.

This fixes https://github.com/codingcyclist/ha_strava/issues/45

### CODE REVIEW

File: custom_components/ha_strava/camera.py [hunk 1]
```diff
@@ -17,7 +17,6 @@
     CONFIG_URL_DUMP_FILENAME,
 )
 from hashlib import md5
-from homeassistant.const import EVENT_TIME_CHANGED
```
Comment (badguy99) [inline custom_components/ha_strava/camera.py:20]: This won't work as it is used on line 55

**Review by badguy99 — CHANGES_REQUESTED** [review]
