### ISSUE TITLE
HA Strava fails to startup with HA 2022.5

### ISSUE THREAD

**Issue by jouster1974** [codingcyclist/ha_strava#45]
HA Strava was all working fine on 2022.4.7....testing on 2022.5 and getting the following error on start

Setup failed for custom integration ha_strava: Unable to import component: cannot import name 'EVENT_TIME_CHANGED' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

Any idea what might be causing the issue...have had a look about and cant see anyone else reporting

**Comment by jartill** [comment]
Yep. This is because there is a breaking change of the time_changed event being removed. Unfortunately the fix is beyond my limited skills

https://developers.home-assistant.io/blog/2022/04/20/saying-goodbye-to-event_time_changed/

**Comment by jouster1974** [comment]
thanks for the update and for taking the time to comment...beyond mine too

**Comment by BertrumUK** [comment]
Same for me. I also had to change the manifest file to use voluptuous 0.13.1 to get to this error otherwise it threw a voluptuous error instead.

**Comment by BertrumUK** [comment]
I’ve got it working again for me by hashing out the offending line. I do get a camera error on a HA restart, but as I do not use the camera, it’s not an issue for me. 

The line is I. The init_py file

`CONF_WEBHOOK_ID,
    EVENT_COMPONENT_LOADED,
    EVENT_CORE_CONFIG_UPDATE,
    EVENT_HOMEASSISTANT_START,
    #EVENT_TIME_CHANGED,`

**Comment by BertrumUK** [comment]
![EF42BB6F-6AE3-4DB3-B4DC-818242A3FB89](https://user-images.githubusercontent.com/22644029/167008772-658466dc-513d-4bc7-9fd5-c7ee3a0371c3.jpeg)

**Comment by jouster1974** [comment]
@BertrumUK   you superstar...I did look through a couple of files for the EVENT_TIME_CHANGED but didn't check this one...now hashed out and working perfectly again..I also don't use images

**Comment by BertrumUK** [comment]
Hashing out line 20 in camera.py clears the error on a restart 

`)
from hashlib import md5
#from homeassistant.const import EVENT_TIME_CHANGED
`

**Comment by jfmfreire** [comment]
i commented a line 28 in init.py, line 20 in camera.py and works for me. 
![image](https://user-images.githubusercontent.com/62487216/167099673-8ec6764c-99c3-481b-a000-cd29ec9e41bc.png)

**Comment by woolf0007** [comment]
i am wondering if this strava is so cumbersome, i set up the connection between strava and fitbit and fitbit is basic integration in HA... What do you think?

**Comment by bjornsivertsen** [comment]
> i am wondering if this strava is so cumbersome, i set up the connection between strava and fitbit and fitbit is basic integration in HA... What do you think?

Does any level of information get lost in transit?

**Comment by youdroid** [comment]
I opened a PR (https://github.com/codingcyclist/ha_strava/pull/46) to remove these two constants from both files. 
Once accepted, everything will work fine again. :+1:

**Comment by craibo** [comment]
I have a working forked version of this here: https://github.com/craibo/ha_strava
